import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import BottomHeader from "@/components/bottom-header";

const boska = localFont({
  src: "../fonts/Boska-Regular.woff",
  variable: "--font-boska",
  weight: "200",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${boska.variable} antialiased`}>
        {children} <BottomHeader />
      </body>
    </html>
  );
}
